--Total revenue generated by male vs. female customers.
SELECT gender, SUM(purchase_amount) AS total_revenue FROM customer_data
GROUP BY gender;


--Which customers used a discount but still spent more than the avg purchase amount?
SELECT customer_id, purchase_amount FROM customer_data
WHERE discount_applied='yes' AND purchase_amount>= (SELECT AVG(purchase_amount) FROM customer_data);


--Top 5 products with the highest avg review rating.
SELECT TOP 5 item_purchased, ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS avg_product_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS FLOAT)) DESC;

--Compare the avg purchase amounts between standard and express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) FROM customer_data
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

--Do suscribed customers spend more? Compare avg spend and total revenue between suscribers and non suscribers.
SELECT subscription_status, COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY avg_spend DESC, total_revenue DESC;

--5 products have thehighest percentage of purchases with discount applied.
SELECT TOP 5 item_purchased,
ROUND(100.0 * AVG(CASE WHEN discount_applied = 'yes' THEN 1.0 ELSE 0.0 END),2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC;


--Segment customers into New, Rturning and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,CASE
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer_data)
SELECT customer_segment, COUNT(*) AS number_of_customers FROM customer_type                 
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


--Top 3 most purchased products within each category.
WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_data
GROUP BY category, item_purchased)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subcribe ?
SELECT subscription_status, COUNT (customer_id) AS repeat_buyers FROM customer_data
WHERE previous_purchases >5
GROUP BY subscription_status;


-- What is the revenue contribution of each age group ?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;

